name: FinAI CI Pipeline

on: 
  push:
    branches: ["main", "develop"]
  pull_requests:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Job para el Backend de Java (Spring Boot)
  build-spring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -f Back-end/payment-service/pom.xml clean package -DskipTests

  # Job para el Gateway (Node.js)
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Back-end/gateway_service/package-lock.json
      - name: Install dependencies
        run: npm ci --prefix Back-end/gateway_service
      - name: Run Lint/Build
        run: npm run build --prefix Back-end/gateway_service --if-present

  # Job para Angular
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Angular dependencies
        run: npm ci --prefix Front-end/FinAI-Front
      - name: Build Angular
        run: npm run build --prefix Front-end/FinAI-Front